name: mystery_dining_edition
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  equatable: any
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  get_it: ^7.6.7
  go_router: ^13.2.1

  # map dependencies
  flutter_map: ^6.1.0
  flutter_map_cache: ^1.5.0
  flutter_map_animations: ^0.5.3

  # dio
  dio: ^5.4.1
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2

  material_floating_search_bar_2: ^0.5.0
  onboarding_overlay: ^3.2.1
  intro_slider: ^4.2.1
  lottie: ^3.1.0

  flutter_native_splash: ^2.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  latlong2: ^0.9.0
  location: ^5.0.3
  permission_handler: ^11.3.0
  flutter_compass: ^0.8.0
  pretty_dio_logger: ^1.3.1
  loggy: ^2.0.3
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  hive_generator: ^2.0.1
  wolt_modal_sheet: ^0.5.0
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.1
  flutter_fortune_wheel: ^1.3.1
  rxdart: ^0.27.7
  url_launcher: ^6.2.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/logo-dark.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/logo-dark.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/icon/logo-dark.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icon/
    - assets/images/
    - assets/env/.env
