name: mystery_dining_edition
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  get_it: ^7.6.7
  go_router: ^13.2.1

  # map dependencies
  flutter_map: ^6.1.0
  flutter_map_cache: ^1.5.0
  flutter_map_animations: ^0.5.3

  # dio
  dio: ^5.4.1
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2

  material_floating_search_bar_2: ^0.5.0
  onboarding_overlay: ^3.2.1
  intro_slider: ^4.2.1

  flutter_native_splash: ^2.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/env/.env
